### PR TITLE
New features

### PR DESCRIPTION
**Pull request by Rylern**

### CODE REVIEW

**Review by petebankhead — CHANGES_REQUESTED** [review]
Looks good!

I've requested some changes above. A few others:

* When the log is empty, the text isn't styled corrected in dark mode - see screenshot below
   * If this is a `Text` object, it may just need styling, e.g. with `-fx-fill: -fx-text-base-color;`
* The warning message should have a color as well
* I think that, to increase their visual impact, the warning and error counts shouldn't be displayed when zero - we don't want users to stop noticing them.
   * This would also avoid the problem of having an item that looks clickable, but doesn't do anything upon being clicked
   * An alternative would be to keep the counts, but decrease their opacity when zero - but that would still have the 'clickable item that isn't actually clickable' issue
* A message appears after saving logs - but I think this is distracting and not really necessary
    * A ControlsFX `Notification` could be used instead, but would introduce a new dependency
    * If `qupath-fxtras` is needed as a dependency at some point, you can use the [`Dialogs` class](https://github.com/qupath/qupath-fxtras/blob/main/src/main/java/qupath/fx/dialogs/Dialogs.java) - this can optionally show notifications if ControlsFX is available, or dialogs if not
* No message appears after pressing the `Copy` button - but I think the user ought to be notified somehow that something has happened
  * I also think the `Copy` button should be slightly wider to make it more prominent and balanced (but only if that can be done with padding, and doesn't require hard-coding the size)

One other possibility that could address the 'notifying the user' issue for saving/copying would be to use the empty space between the counts and copy button to display a label.

Something I think might be quite nice - albeit more awkward to code - would be to show a message label after copying/saving in this area, and then fading it out over a few seconds by decreasing opacity using a JavaFX animation/transition.

So upon pressing `Copy`, for example, a message would show temporarily with either `Copied!` or `Copied *n* messages to clipboard`

Mentioning @alanocallaghan and @finglis in case they also have opinions here.

log-dark

**Comment by petebankhead** [comment]
Also: consider what the behavior should be whenever errors are not displayed (for example), by clicking the toggle button at the top.

Currently, the error count shows are 0, but this is wrong and misleading.

I propose that if warnings/errors are being filtered out, the counts label should state `Errors are hidden!` or `Warnings are hidden!` until they are shown again.

This also acts as a way to teaching the user what the toggle buttons actually do.

What do you think?

**Comment by petebankhead** [comment]
Thanks, I still see the 0 error messages (although it's no longer clickable).

I think not showing that information would be better. If it's always visible, then I expect the user will mentally filter out the red text in the bottom left corner - and not notice when it is important. I think that the error count only showing when errors exist is more effective.

(The alternative would be to show the counts but only color the text when the warning or error count is non-zero... since the colored text is much more noticeable, and the main thing is to ensure users notice when there are errors)

The default warning color also has quite low contrast when not using dark mode:

log-gold

An alternative to `gold` would be `darkorange`, which I think looks ok both light and dark.

log-darkorange

Finally, I like the fading of the message. 

I initially thought it was broken, because nothing happened when I pressed 'Copy'... although then later realised it's because I hadn't selected anything. So I think the 'Copy' button should only be enabled if messages are selected, to stop people like me getting confused.

I also think it would be better to right-align the text (bringing it closer to the copy button), and also don't end it with a full stop (because it feels very 'final'....)

**Comment by Rylern** [comment]
Thanks, every comments should have been addressed.

**Comment by petebankhead** [comment]
Thanks, I like it!

I think the behavior is very good and it's fine to merge - there are just two small visual things:
* I think the `Level: INFO` should be the same font size as the buttons next to it (i.e. have the same CSS style class applied)
   * This might also apply to the `Copy` button
* The spacing at the bottom left feels wrong to me - the gap between the warnings and total count is too long, and the use of (brackets) around the total count also feels strange whenever it can stand alone (e.g. after a call to *Edit &rarr; Clear logs*).

But since these are more aesthetic things, it would be good to have more opinions than just mine @alanocallaghan @finglis @lauranicolass 

Overall, I think the new log viewer is looking great - and I'm already finding it enormously useful during debugging :)

Log-viewer screenshot

**Comment by Rylern** [comment]
Thanks, every comments should have been addressed. However I'm not sure about the size of the `Copy` button, don't you think it's too small now?

**Comment by petebankhead** [comment]
Yes, could be... or at least it should be the same size as the warnings / total?

I think the small size looks good for the toggle buttons at the top. The Level label looked too big for me at 'full size', but somehow seems smaller than the toggle buttons (even though it's probably an illusion, due to not being upper case and not having the button surroundings).

In the CSS you can change the font size by a percentage, so could perhaps adjust some controls by 80% and others by 90% - to find a balance.

In any case, I'd merge this for now - can certainly explore other adjustments to the CSS, and perhaps even provide people in the group with some screenshots to vote on.

**Pull request merged**
